import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Noto_Sans } from "next/font/google";
import { Noto_Sans_JP } from "next/font/google";
const notoSans = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: ["latin"],

})

const notoSansJP = Noto_Sans_JP({
  variable: "--font-noto-sans-jp",
  subsets: ["latin"],
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${notoSans.variable} ${notoSansJP} antialiased`} suppressHydrationWarning={true}
      >
        {children}
      </body>
    </html>
  );
}
